config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :users
  get 'user_index', to: 'users#index'
  resources :products
  root 'products#index'
  get 'create_payment', to: 'payments#create_payment'
  get 'order_place', to: 'payments#order_place'
  get 'payment_failed', to: 'payments#payment_failed'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<ul>
    <% if user_signed_in? %>
        <li><div>Welcome <%= current_user.email %></div></li>
        <li><div><%= button_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% if current_user.role=="admin" %>
            <li><div><%= button_to "User", user_index_path, method: :get %></li>
        <% end %>
    <% else %>
        <li><div><%= button_to "Log in", new_user_session_path, method: :get %></li>
        <li><div><%= button_to "Sign up", new_user_registration_path, method: :get %></li>
    <% end %>
</ul>
<style>

 ul {
   list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
  position: -webkit-sticky; /* Safari */
  position: sticky;
  top: 0;
 }
 
 li {
   float: left;
 }
 
 li div {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
 }
 
 li a:hover {
   background-color: #111;
 }

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentGatewayIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>